#!bin/bash
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'
yellow='\033[33;1m'
figlet -t WELCOME
echo $yellow "==================================="
echo $white "#         TOOLS INSTALLER          #"
echo $white "#                                  #"
echo $white "# CREATOR : Tn.Kuuhaku             #"
echo $white "# VERSI   : 1.0                    #"
echo $yellow "==================================="
echo
read -p Mulai..? Klik Enter
sleep 2
echo $purple "LIST TOOLS : "
echo
echo $white "===================================="
echo $cyan "#       1.Deface Webdav             #"
echo $cyan "#       2.Web Deface Webdav         #"
echo $white "===================================="
echo
read -p "PILIH ANGKA :" bro;
echo
if [ $bro = 1 ] || [ $bro = 1 ]
then
git clone https://github.com/TnKuuhaku/webdav
cd webdav
sh webdav.sh
fi

echo
if [ $bro = 2 ] || [ $bro = 2 ]
then
git clone https://github.com/TnKuuhaku/web
cd web
sh web.sh
fi
